[package]
name = "generic_game"
version = "0.0.2"
authors = ["Jonesey13 <adj27@cam.ac.uk>"]

[dependencies]
multiinput = "0.0.7"
glium = "0.16.0"
nalgebra = "*"
num = "*"
time = "*"
unicode-normalization = "*"
rusttype = { git = "https://github.com/Jonesey13/rusttype.git", rev = "a809432" }
rand = "*"
lazy_static = "*"

[dependencies.bitflags]
version = "*"
