[package]
name = "generic_game"
version = "0.1.0"
authors = ["Jonesey13 <adj27@cam.ac.uk>"]

[dependencies]
multiinput = {version = "*", path = "C:/Users/Jonesey13/Projects/multiinput"}
glium = "*"
glium_text =  {version = "*", path = "C:/Users/Jonesey13/Projects/glium_text"}
log = "*"
env_logger = "*"
nalgebra = "*"
num = "*"
backtrace = "*"
