[package]
name = "generic_game"
version = "0.1.0"
authors = ["Jonesey13 <adj27@cam.ac.uk>"]

[dependencies]
multi-input = "*"
glium = "*"
glium_text = "*"
nalgebra = "0.7.0"
num = "*"
time = "*"

[dependencies.bitflags]
version = "*"
