[package]
name = "generic_game"
version = "0.0.1"
authors = ["Jonesey13 <adj27@cam.ac.uk>"]

[dependencies]
multiinput = "0.0.6"
glium = "0.16.0"
nalgebra = "*"
num = "*"
time = "*"
unicode-normalization = "*"
rusttype = { git = "https://github.com/Jonesey13/rusttype.git", rev = "a2fd94ff" }
rand = "*"
lazy_static = "*"

[dependencies.bitflags]
version = "*"
